name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  linuxamd64build:
    name: build x-ui MPS64 version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: build linux Mips64 version
        run: |
          sudo apt-get update
          wget -P ~ https://musl.cc/mips64-linux-musl-cross.tgz
          tar -xvf ~/mips64-linux-musl-cross.tgz
          CGO_ENABLED=1 GOOS=linux GOARCH=mips64 CC=$PWD/mips64-linux-musl-cross/bin/mips64-linux-musl-gcc go build -o xui-release -v main.go
          mkdir x-ui
          cp xui-release x-ui/xui-release
          cp x-ui.service x-ui/x-ui.service
          cp x-ui.sh x-ui/x-ui.sh
          cd x-ui
          mv xui-release x-ui
          mkdir bin
          cd bin
          wget https://github.com/XTLS/Xray-core/releases/download/v1.8.7/Xray-linux-mips64.zip
          unzip Xray-linux-mips64.zip
          rm -f Xray-linux-mips64.zip geoip.dat geosite.dat LICENSE README.md
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          wget -O geoip_IR.dat https://github.com/chocolate4u/Iran-v2ray-rules/releases/latest/download/geoip.dat
          wget -O geosite_IR.dat https://github.com/chocolate4u/Iran-v2ray-rules/releases/latest/download/geosite.dat
          wget -O geoip_VN.dat https://github.com/vuong2023/vn-v2ray-rules/releases/latest/download/geoip.dat
          wget -O geosite_VN.dat https://github.com/vuong2023/vn-v2ray-rules/releases/latest/download/geosite.dat
          mv xray Xray-linux-mips64
          cd ..
          cd ..
      - name: package
        run: tar -zcvf x-ui-linux-mips64.tar.gz x-ui
      - name: upload
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: x-ui-linux-mips64.tar.gz
          asset_name: x-ui-linux-mips64.tar.gz
          prerelease: true
